### ISSUE TITLE
Generating zkif files in test/

### ISSUE THREAD

**Issue by m0bi5** [elefthei/spartan-zkinterface#3]
Hi,

I was curious to know how one can generate zkif files as three parts (inp, wtns, circuit). I tried using pySNARK but it outputs only 2 zkif files. More about it here - https://github.com/meilof/pysnark#using-pysnark-zkinterface-backend-bellman-bulletproofs

**Comment by edauterman** [comment]
@m0bi5 Did you ever figure this out? ZoKrates (https://github.com/QED-it/ZoKrates/blob/zkinterface/zokrates_core/src/proof_system/zkinterface.rs) only outputs 2 zkif files.

**Comment by m0bi5** [comment]
@edauterman unfortunately nope :(
